//
//  afterglowdata
//
//  Copyright © 2026 Unpxre (GitHub: UnpxreTW)
//  Licensed under the Apache License 2.0. See LICENSE for details.
//
//  SPDX-License-Identifier: Apache-2.0

/// 組出 `UAOTable.swift` 全文的 renderer：把 ``DecodeTableGenerator`` 與 ``EncodeTableGenerator``
/// 的產出組成單一 generated Swift 檔（檔頭、來源與表示法註記、decode 六 zone 常數、
/// encode key／value 常數、聚合 property）。
enum UAOTableRenderer {

	/// 組出完整檔案文字；`decoded` / `encoded` 為兩個方向各自斷言與 pack 後的產出。
	static func render(decoded: DecodeTableGenerator.Result, encoded: EncodeTableGenerator.Result) -> String {
		header(encoded: encoded) + enumBody(decoded: decoded, encoded: encoded)
	}

	/// 檔頭：SPDX header、GENERATED BY 註記、來源與兩個方向的表示法說明。
	static func header(encoded: EncodeTableGenerator.Result) -> String {
		"""
		//
		//  PTTBig5Codec
		//
		//  Copyright © 2026 Unpxre (GitHub: UnpxreTW)
		//  Licensed under the Apache License 2.0. See LICENSE for details.
		//
		//  SPDX-License-Identifier: Apache-2.0

		//  GENERATED BY `swift run afterglowdata generate` — DO NOT EDIT.
		//  來源：uao250 b2u（完整 \(Generator.expectedB2UCount) 筆、126 lead × 157 trail 滿格）與
		//  uao250 u2b（\(Generator.expectedU2BCount) 筆、含 \(Generator.expectedU2BSentinelCount) 筆 0xFFFD 無對應哨兵）、
		//  取自 moztw/www.moztw.org@\(Generator.sourcePin.prefix(12))、SHA-256 驗證見產生器常數。
		//  decode 表示法：value-only 密集陣列、分六 zone 之 base64 varint 串
		//  （首值 LEB128、後續 zigzag-LEB128 差分；key 由 Big5 pointer 公式推導、不儲存）。
		//  encode 表示法：u2b 稀疏 Unicode key 無法套用密集陣列，改用遞增 key／value 兩段
		//  base64 varint 串 + 二分搜尋；僅收 \(encoded.keys.count) 筆「有對應」列
		//  （canonical \(Generator.expectedCanonicalCount) + best-fit \(Generator.expectedBestFitCount)），
		//  0xFFFD 哨兵不落表、查無即語意等價於 nil。

		// swiftformat:disable all
		// 原因：本檔為產生器機械產出，格式規則對其無指引意義。


		"""
	}

	/// `enum UAOTable { ... }` 本體：來源識別、decode 六 zone 常數、encode key／value 常數、聚合 property。
	static func enumBody(decoded: DecodeTableGenerator.Result, encoded: EncodeTableGenerator.Result) -> String {
		"""
		enum UAOTable {

		\t/// 表來源識別（uao250 ＝ UAO 2.50）。
		\tstatic let source = "uao250"

		\t/// 解碼表總筆數（126 lead × 157 trail 滿格）。
		\tstatic let decodeCount = \(Generator.expectedB2UCount)

		\t// swiftlint:disable line_length
		\t// 原因：blob 行長由資料量決定。
		\(renderDecodeZones(decoded))
		\t/// encode key 陣列（遞增排序、去重的 Unicode scalar，varint 差分；與 encodeValues 索引對齊）。
		\tstatic let encodeKeys: StaticString = "\(encoded.packedKeys)"

		\t/// encode value 陣列（對應 2-byte 原始輸出值 `(byte0 << 8) | byte1`，varint 差分）。
		\tstatic let encodeValues: StaticString = "\(encoded.packedValues)"
		\t// swiftlint:enable line_length

		\t/// encode 表筆數（u2b 表中「有對應」的 canonical + best-fit 筆數）。
		\tstatic let encodeCount = \(encoded.keys.count)

		\t/// 依 lead 序串接＝完整 pointer 空間（餵 ``UAODecodeTable``）。
		\tstatic var zones: [StaticString] {
		\t\t[zoneUserDefined, zoneSymbols, zoneHanziL1, zoneKanaCyrillic, zoneHanziL2, zoneExtension]
		\t}
		}

		"""
	}

	/// decode 六 zone 的 `static let` 常數區塊（含各自筆數 / 內容說明的文件註解）。
	static func renderDecodeZones(_ decoded: DecodeTableGenerator.Result) -> String {
		var constants = ""
		for (zone, packed) in zip(DecodeTableGenerator.zones, decoded.packedZones) {
			let low: String = .init(zone.leadLow, radix: 16, uppercase: true)
			let high: String = .init(zone.leadHigh, radix: 16, uppercase: true)
			constants += """

				\t/// lead 0x\(low)–0x\(high)、\(zone.expectedCount) 筆——\(zone.comment)。
				\tstatic let \(zone.name): StaticString = "\(packed)"

				"""
		}
		return constants
	}
}
